#!/bin/bash

echo "VPSHM - Virtual Private Server Host Manager Installer"
echo ""

#create scripts folder if it doesn't exist
if [ ! -d "/VPSHM-scripts" ]
then
    echo "VPSHM-scripts folder doesn't exist. Creating now..."; res = $(mkdir -p -- "/VPSHM-scripts" 2>&1| grep xy); echo $res
else
    echo "VPSHM-scripts folder exists"
fi

echo "Update the system and install necessary packages"
echo "$(yum install curl sudo 2>&1 | grep xy)"
