#!/bin/bash

#usage cd /tmp && wget -O installer wget https://raw.githubusercontent.com/platinumindustries/VPSHM/master/installer && sh installer

echo "VPSHM - Virtual Private Server Host Manager Installer"
echo ""

#create scripts folder if it doesn't exist
if [ ! -d "/VPSHM-scripts" ]
then
    echo "VPSHM-scripts folder doesn't exist. Creating now..."; 
    mkdir -p -- '/VPSHM-scripts'
    echo "VPSHM-scripts folder created"
else
    echo "VPSHM-scripts folder exists"
fi

echo "Run Nodejs Installer script";
cd /VPSHM-scripts && wget -O nodejs https://raw.githubusercontent.com/platinumindustries/VPSHM/master/scripts/nodejs && sh nodejs

echo "Run MYSQL Installer script";
cd /VPSHM-scripts && wget -O mysql https://raw.githubusercontent.com/platinumindustries/VPSHM/master/scripts/mysql && sh mysql

echo "Cleaning up" 
cd /tmp && rm -fv installer
