#!/bin/bash

#usage wget https://raw.githubusercontent.com/platinumindustries/VPSHM/master/installer && sh installer

echo "VPSHM - Virtual Private Server Host Manager Installer"
echo ""

#create scripts folder if it doesn't exist
if [ ! -d "/VPSHM-scripts" ]
then
    echo "VPSHM-scripts folder doesn't exist. Creating now..."; 
    RES="$(mkdir -p -- '/VPSHM-scripts')"; 
    echo "${RES}"
else
    echo "VPSHM-scripts folder exists"
fi

echo " Run Nodejs Installer script";NODEJS="$(cd /tmp && wget https://raw.githubusercontent.com/platinumindustries/VPSHM/master/installer && sh nodejs)"; echo "${NODEJS}"
