#!/bin/bash

echo ""
echo "VPSHM - Virtual Private Server Host Manager Installer Shell"
echo ""
echo "Checking CouchDB"
echo "Adding CouchDB YUM repo"

cat <<EOF | sudo tee -a /etc/yum.repos.d/bintray-apache-couchdb-rpm.repo
[bintray--apache-couchdb-rpm]
name=bintray--apache-couchdb-rpm
baseurl=http://apache.bintray.com/couchdb-rpm/el$releasever/$basearch/
gpgcheck=0
repo_gpgcheck=0
enabled=1
EOF

echo "Preparing to install CouchDB"
yum -y install epel-release && yum install curl && yum install couchdb

echo "Running first time setup..."
curl -X PUT http://127.0.0.1:5984/_users
curl -X PUT http://127.0.0.1:5984/_replicator

echo "Allow access from web"
sed -i 's/;port = 5984/port = 5984/g' /usr/local/etc/couchdb/local.ini
sed -i 's/;bind_address = 127.0.0.1/bind_address = 0.0.0.0/g' /usr/local/etc/couchdb/local.ini

echo "Set couchdb to start on as daemon on boot"
ln -s /usr/local/etc/rc.d/couchdb /etc/init.d/couchdb
chkconfig --add couchdb
chkconfig --level 345 couchdb on

echo "Modify firewall rules"
firewall-cmd --permanent --zone=public --add-port=5984/tcp
firewall-cmd --reload

echo "All done"
